### ISSUE TITLE
Прокрутка на мобильном

### ISSUE THREAD

**Issue by oleg-tgn** [lazaryan/lazaryan.github.io#15]
Появляется прокрутка и горизонтальная и вертикальная. Какие-то элементы выходят за максимальную ширину

![image](https://user-images.githubusercontent.com/16413346/30782061-25beb5ee-a133-11e7-9cc7-ffa9b7bbf918.png)

**Comment by lazaryan** [comment]
Изменил отступы и навигацию , теперь прокрутка не мешает
